version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: poc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: poc_database
      MYSQL_USER: poc_user
      MYSQL_PASSWORD: poc_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 